title: jekyll-theme-cayman

header_pages:
  - index.md
  - instructions.md
  - wavenet.md
  - aws_preprocessing_parallelization.md
  - aws_model_parallelization.md
  - reproducibility.md

theme: jekyll-theme-cayman